"""Shared file schemas and folder contracts for ElectroMacroDiff V5.2."""

from __future__ import annotations

PROJECT_DIRS = [
    "00_project_registry",
    "01_raw_data/chembl",
    "01_raw_data/bindingdb",
    "01_raw_data/pubchem",
    "01_raw_data/pdb",
    "01_raw_data/literature",
    "02_curated_data",
    "03_features/ligand_graphs",
    "03_features/conformers",
    "03_features/splits",
    "04_models_checkpoints/se3_flow",
    "04_models_checkpoints/se3_flow_pretrain",
    "04_models_checkpoints/baseline_models",
    "04_models_checkpoints/v5_3_anchor",
    "04_models_checkpoints/v5_3_anchor_pretrain",
    "04_models_checkpoints/v5_3_linker_size",
    "04_models_checkpoints/v5_3_linker_size_pretrain",
    "05_generated_candidates/se3",
    "05_generated_candidates/selfies",
    "05_generated_candidates/rdkit",
    "05_generated_candidates/macrocycle_linker",
    "05_generated_candidates/merged",
    "06_docking/receptor",
    "06_docking/ligands_sdf",
    "06_docking/ligands_pdbqt",
    "06_docking/poses",
    "06_docking/scores",
    "06_docking/images",
    "07_admet_synthesis",
    "07_admet_synthesis/aizynth_routes",
    "08_final_ranking",
    "09_reports",
    "10_notebooks",
    "11_logs",
]

CURATED_LIGAND_COLUMNS = [
    "mol_id",
    "source",
    "source_id",
    "canonical_smiles",
    "inchikey",
    "activity_type",
    "activity_value_nM",
    "p_activity",
    "target",
    "assay_id",
    "confidence_score",
    "max_ring_size",
    "has_macrocycle_12_20",
    "has_constrained_ring_8_11",
    "split",
    "notes",
]

LIGAND_FEATURE_COLUMNS = [
    "mol_id",
    "canonical_smiles",
    "mw",
    "logp",
    "tpsa",
    "hbd",
    "hba",
    "rotatable_bonds",
    "qed",
    "num_atoms",
    "num_heavy_atoms",
    "num_rings",
    "max_ring_size",
    "formal_charge",
    "passes_rdkit",
    "passes_basic_filters",
]

GENERATED_CANDIDATE_COLUMNS = [
    "candidate_id",
    "source_generator",
    "parent_mol_id",
    "canonical_smiles",
    "inchikey",
    "valid_rdkit",
    "unique_flag",
    "novel_flag",
    "mw",
    "logp",
    "tpsa",
    "hbd",
    "hba",
    "rotatable_bonds",
    "qed",
    "sa_score",
    "murcko_scaffold",
    "max_ring_size",
    "has_macrocycle_12_20",
    "has_constrained_ring_8_11",
    "passes_basic_filters",
    "generation_notes",
]

DOCKING_SCORE_COLUMNS = [
    "candidate_id",
    "smiles",
    "docking_engine",
    "receptor_pdb",
    "grid_center_x",
    "grid_center_y",
    "grid_center_z",
    "grid_size_x",
    "grid_size_y",
    "grid_size_z",
    "best_score",
    "pose_rank",
    "pose_file",
    "pose_image",
    "control_or_generated",
    "notes",
]

FINAL_RANKING_COLUMNS = [
    "rank",
    "candidate_id",
    "source_generator",
    "smiles",
    "inchikey",
    "docking_score",
    "pose_score",
    "qed",
    "sa_score",
    "admet_score",
    "safety_proxy_score",
    "novelty_score",
    "diversity_cluster",
    "final_weighted_score",
    "decision",
    "main_risk",
]

REGISTRY_COLUMNS = [
    "run_id",
    "stage",
    "started_at",
    "finished_at",
    "status",
    "input_path",
    "output_path",
    "molecules_in",
    "molecules_out",
    "random_seed",
    "notes",
]

ARTIFACT_COLUMNS = [
    "artifact_id",
    "stage",
    "path",
    "artifact_type",
    "owner",
    "created_at",
    "status",
    "notes",
]
